### ISSUE TITLE
HA 재부팅시 unit of measurement: 원 으로 인한 에러 발생

### ISSUE THREAD

**Issue by kkqq9320** [GrecHouse/gas_station_korea#1]
![원 error](https://github.com/GrecHouse/gas_station_korea/assets/129671069/691ce60d-c64d-4179-9c1f-4e0e5305914d)

2024-02-02 12:01:38.354 ERROR (MainThread) [custom_components.hacs] <QueueManager> 'utf-8' codec can't decode byte 0xb2 in position 7167: invalid start byte

Hello.
I want to express my appreciation for the excellent component you've provided, which I've been using successfully.

I'm reaching out regarding an issue I encountered while addressing HA reboot errors. I'm getting a 'utf-8' error related to hacs queueManager. Could you please assist with this matter?

It seems like there might be an encoding error due to the Korean character "원" in the "unit_of_measurement: 원" property of the sensor.

Is there a way for me to resolve this issue?

As an extra note: After deleting the sensor and rebooting, I did not encounter any related errors.

안녕하세요.
이슈 작성에 앞서 좋은 컴포넌트 만들어주셔서 잘 사용하고 있다는 감사의 말씀 드립니다.

다름이 아니고 HA 재부팅시 오류를 정리하던 중에, hacs queueManager 'utf-8' 에러가 뜨고 있어 문의 남깁니다.

찾아보니 센서의 속성중 하나인 "unit_of_measurement: 원" 에서 "원"이 한글어라 인코딩 에러가 발생하는 것 같습니다.

제가 해결할 수 있는 방법이 있을까요?

번외: 센서를 지우고 재부팅하니 관련 오류가 발생하지 않았습니다

**Comment by GrecHouse** [comment]
안녕하세요. 
'원' 처리 부분을 바꿔봤는데 제 환경에서는 이전 이후 모두 에러가 발생하지 않아 😅 제대로 동작이 되는지 알 수가 없네요.
1.0.1 버전으로 업데이트한 후에도 에러가 발생하면 다시 알려주세요. 감사합니다.

**Comment by kkqq9320** [comment]
빠른 피드백 정말 감사드립니다
제 HA가 뭔가 잘못됐나 봅니다... 업뎃후에도 동일하게 발생하네요 다른 방법도 찾아보겠습니다 ㅠㅠ
