### ISSUE TITLE
주유소값 key 10자리수 등록시 오류

### ISSUE THREAD

**Issue by noxcrow** [GrecHouse/gas_station_korea#3]
주유소값 key 10자리수 등록시 결과값을 불러올수가 없습니다.

예 ) https://place.map.kakao.com/2099468525 # 한길송정주유소

![image](https://github.com/user-attachments/assets/91c772e0-658d-4b9c-9867-b932a2bfe4b3)

**Comment by GrecHouse** [comment]
안녕하세요. 자리수와는 관계가 없고, 해당 주유소에서 가격 정보를 제공하지 않고 있습니다. 센서로 불러오기 위해서는 카카오맵에서 주유소 정보를 볼 때 가격 정보가 조회되어야 합니다. 
![SmartSelect_20241031_204943_Chrome](https://github.com/user-attachments/assets/8f163750-45d6-4a64-b813-263b4fb0ec9c)
